### ISSUE TITLE
how does an `enqueue`d job know when it is completed

### ISSUE THREAD

**Issue by davetayls** [scttnlsn/monq#34]
I'm `enqueue`ing jobs but i can't work out how the job returned in the `enqueue` callback can be notified of when it is completed by a separate worker.

I was expecting to be able to do something like:

``` javascript
queue.enqueue('jobname', function(err, job) {
  job.on('complete', function() { console.log('complete'); });
});
```

**Comment by brianreese** [comment]
I have a worker which spawns a child process. The parent process listens for events on the spawned child process, and eventually calls the enqueued job's callback once complete - however, my worker doesn't seem to ever end the current job and grab a new one. 

I don't need to notify the enqueuing process of the job's progress, just trying to figure out how to have my worker process more than a single item from the queue. Are there any special considerations when processing my queue in this way (e.g. incorporating the child process), or am I maybe just missing something in the way I've set up my worker?

**Comment by brianreese** [comment]
Nevermind, please ignore my previous comment. The job wasn't actually completing, and the promise I setup never actually resolved.
