### ISSUE TITLE
datestamp is redundant.. mongo _id's have a built in date

### ISSUE THREAD

**Issue by medmr1** [scttnlsn/monq#37]
I was moving to 0.3.1 to get rid of this warning: 
(node) warning: possible EventEmitter memory leak detected. 51 listeners added. Use emitter.setMaxListeners() to increase limit.

but I see that there are several new fields stored in the job object.
if datestamp is for creation time, it's really not needed.
_id.getTimestamp() will give you that.

**Comment by scttnlsn** [comment]
I'd be interested to see some performance data to back this up but, for now, I'm going to close the issue.  Feel free to reopen if you still think this is an important change.
