### ISSUE TITLE
Eliminate Polling

### ISSUE THREAD

**Issue by martindale** [scttnlsn/monq#38]
Using polling for a worker queue isn't an elegant model, and results in a [configurable but] suboptimal 5-second delay before jobs are processed on an empty queue.

Perhaps utilizing tailable cursors would be a reasonable approach, or even hooking into the oplog (see [TorchlightSoftware/mongo-watch](https://github.com/TorchlightSoftware/mongo-watch)).

**Comment by scttnlsn** [comment]
Closing (but still open to a PR).
