### ISSUE TITLE
Check for existence of callbacks

### ISSUE THREAD

**Issue by dhritzkiv** [scttnlsn/monq#42]
I think the code should check for the existence for callbacks, specifically on [this line](https://github.com/scttnlsn/monq/blob/master/lib/job.js#L37). This would be useful for when you enqueue a task, but don't want to provide a callback.

A simple `callback && callback()` might work.

**Comment by scttnlsn** [comment]
https://github.com/scttnlsn/monq/commit/cf0ea8019e7094448dda29eac5936774ac3d607b

Thanks!
