### ISSUE TITLE
Allow scalar in worker()?

### ISSUE THREAD

**Issue by vicary** [scttnlsn/monq#46]
Got an error on my first try.
```
node_modules/monq/lib/connection.js:15
    var queues = queues.map(function (queue) {
                        ^
TypeError: undefined is not a function
```

It would be more intuitive to support `client.worker(queue);` for simple projects.

**Comment by scttnlsn** [comment]
Good suggestions, thanks!  Added here: https://github.com/scttnlsn/monq/commit/a4c5fa249d82cbbd981e67f9e6a2f39958b16abb
