### ISSUE TITLE
Rate Limit

### ISSUE THREAD

**Issue by vertangelx** [scttnlsn/monq#47]
I currently have 1 worker polling a queue anad the job takes 1 sec to complete. How can we limit the worker to complete only 1 job per X minutes?

**Comment by meteorjs3000** [comment]
Tried `var worker = client.worker([userEmail], {interval: 60000})` but the worker is consuming jobs without any interval

**Comment by sofian86** [comment]
no rating on route as 1 location got a few route to take

**Comment by scttnlsn** [comment]
I think this could be accomplished by listening to worker events, counting the number of failed and completed job, and starting/stopping the worker accordingly.  I don't see any need to build in a worker rate/interval.  Please reopen if I'm misunderstanding or missing something!
