### ISSUE TITLE
Limit to N Jobs in X Hours

### ISSUE THREAD

**Issue by meteorjs3000** [scttnlsn/monq#48]
Thanks for the mongdb alternative to Kue!

How can the number of jobs be limited to N jobs every X hours? For example, if there are 10 jobs queued up, I want the worker to do only 5 jobs (1 job every minute) starting at say 12pm. Then do the remaining 5 jobs (polling at the same 1 job/min) but at 6pm. So its like limiting to 5 jobs every 6 hours.

**Comment by scttnlsn** [comment]
This is sort of a duplicate of #47 (rate limiting).  I think the scheduling is a bit beyond the scope of this library.  Would it be possible to start and stop workers via some other sort of process scheduler?
