### ISSUE TITLE
Provide safe way to shutdown the workers

### ISSUE THREAD

**Issue by cberigan** [scttnlsn/monq#67]
I've been looking for persistent lightweight queue services such as this. One particular need that I require is that the queue be able to pick up any jobs that were not finished due to automated deployments and/or abrupt shutdowns. 

Anyway, I feel that it may be useful to provide an interface client/workers to safely shutdown. Just for transparency I have provided a workaround that does just that.

```
function gracefulShutdown(){
    debug('zip worker marking dequeued job back as queued');
    client.db.collection('jobs').findAndModify({
        query: {status: 'dequeued', queue: 'q1'},
        update: {$set : {status: 'queued', dequeued: null}},
        new: true
    },function(err,doc,lastErrorObject){
        process.exit(0);
    });
}

process.on('SIGTERM', gracefulShutdown);
process.on('SIGINT' , gracefulShutdown);
```
This is just an example, but the same idea could be applied somewhere in the interface to mark all queue types in the job queue back to enqueue. This way they'll be picked up at startup again.

**Comment by scttnlsn** [comment]
I think this sort of thing should probably happen in application code since the startup/shutdown code should only be run when there are no active workers reading from the collection.
