### ISSUE TITLE
Do we need to use Web Workers too ?

### ISSUE THREAD

**Issue by sincerekamal** [scttnlsn/monq#70]
Hi,
Just curious to know whether we need to have web worker inside the monq to worker to make it more fast ? 
Further questions are,
1. Does Monq worker methods block the Node.js Event loop ? which means, any block or hang in Monq affect the Node.js event loop(or I/O) ? 
2. Do I need include any Web worker library too ?

**Comment by scttnlsn** [comment]
There's nothing special about the worker methods so calling blocking code would indeed block the event loop.  You're free to use whatever additional mechanisms you'd like in the worker methods (including web workers if desired).
